docker run -d \
  --name llama-qwen38 \
  --device=nvidia.com/gpu=all \
  -p 8086:8080 \
  -v /home/pxp/Documents/code/llamacpp/qwenb:/models:z \
  --entrypoint /app/llama-server \
  ghcr.io/ggml-org/llama.cpp:full-cuda13 \
  -m /models/Qwen3.8-27B-UD-Q4_K_M.gguf \
  --mmproj /models/mmproj-BF16.gguf \
  --host 0.0.0.0 \
  --port 8080 \
  -ngl 99 \
  --parallel 1 \
  --spec-type draft-mtp \
  --spec-draft-model /models/mtp-Qwen3.8-27B-Q4_0.gguf \
  --spec-draft-n-max 3 \
  --spec-draft-ngl 99 \
  --jinja \
  --reasoning-format deepseek \
  --temp 0.8 \
  --top-p 0.9 \
  --top-k 40 \
  --min-p 0.0 \
  --repeat-penalty 1.1 \
  --repeat-last-n 64
